### ISSUE TITLE
.lucky needs to bind to the "I'm feeling lucky search"

### ISSUE THREAD

**Issue by Jayflux** [hashweb/bot#9]
.lucky needs to bind to the "I'm feeling lucky search"

**Comment by mrcrilly** [comment]
I'm not entirely sure (because I can't see config.js), but I believe the '.lucky' command is hitting the 'lib/feelinglucky' library. If it is, then it's already behaving in the manner you suggested:

https://github.com/hashweb/bot/blob/master/lib/feelinglucky/index.js#L21-L31

```javascript
if (results && results[0]) {
  // ...
} // ...
```

You can see here this code already fetches and processes result[0], the first result in the JSON retrieved from Google's API, which means it's acting in the same way as the "I'm Feeling Lucky" feature of Google's Search service.

I'm not sure, however, if you meant "Microsoft Bing" with your, "to bing to" wording. That's a bit confusing.

**Comment by Jayflux** [comment]
Oops!
I did mean Bind, and i will try that out when i next fire up the bot.
Thanks for your reply!

**Comment by Jayflux** [comment]
Yup, this is built in
